[package]
name = "modren_jaba"
version = "1.0.5"
edition = "2024"
license = "MIT"
authors = ["Reiz","xiaole233/Rov-Waff"]

[dependencies]
chrono = "0.4.41" #哇当时真的写成Cirno了
fmt = "0.1.0"
gtk4 = "0.9.7"
regex = "1.11.1"
webbrowser = "1.0.5"
